### ISSUE TITLE
Error message not retrieved correctly

### ISSUE THREAD

**Issue by xpillons** [Azure/azurehpc#232]
[2020-04-21 10:39:33] error: Provisioning failed
  Resource : rgs01 - ResourceDeploymentFailure
  Message  : The resource operation completed with terminal provisioning
             state 'Failed'.
Traceback (most recent call last):
  File "/home/xavier/azurehpc/pyazhpc/azhpc.py", line 625, in <module>
    args.func(args)
  File "/home/xavier/azurehpc/pyazhpc/azhpc.py", line 407, in do_build
    details_code = props["statusMessage"]["error"]["details"].get("code", "")
AttributeError: 'list' object has no attribute 'get'

The deployment error in the portal is 
 {"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"OverconstrainedAllocationRequest\",\r\n \"message\": \"Allocation failed. VM(s) with the following constraints cannot be allocated, because the condition is too restrictive. Please remove some constraints and try again. Constraints applied are:\\n - Proximity Placement Group\\n\"\r\n }\r\n ]\r\n }\r\n}"},{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"OverconstrainedZonalAllocationRequest\",\r\n \"message\": \"Allocation failed. VM(s) with the following constraints cannot be allocated, because the condition is too restrictive. Please remove some constraints and try again. Constraints applied are:\\n - Proximity Placement Group\\n\"\r\n }\r\n ]\r\n }\r\n}"}]}

**Comment by xpillons** [comment]
Another kind of error not catch
{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "Conflict",
      "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"AllocationFailed\",\r\n        \"message\": \"Allocation failed. We do not have sufficient capacity for the requested VM size in this region. Read more about improving likelihood of allocation success at http://aka.ms/allocation-guidance\"\r\n      }\r\n    ]\r\n  }\r\n}"
    },
    {
      "code": "Conflict",
      "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"OverconstrainedAllocationRequest\",\r\n        \"message\": \"Allocation failed. VM(s) with the following constraints cannot be allocated, because the condition is too restrictive. Please remove some constraints and try again. Constraints applied are:\\n  - Low Priority VMs\\n  - Preemptible VMs (VM might be preempted by another VM with a higher priority)\\n  - VM Size\\n\"\r\n      }\r\n    ]\r\n  }\r\n}"
    }
  ]
}

**Comment by xpillons** [comment]
fixed in #274
