### ISSUE TITLE
cyclecloud8 config fails on "authorization.check_datastore_permissions"'

### ISSUE THREAD

**Issue by tbugfinder** [Azure/azurehpc#497]
https://github.com/Azure/azurehpc/blob/1adbceb6dac2151b5cffd76cc837482245fc42fa/scripts/cyclecloud8_config.py#L200

Hello,

whenever I execute cyclecloud8_config.py (using cyclecloud 8.1.1) it fails at the given command:
```
Password specified, using it as the admin password
Storage account specified, using it as the default locker
CycleCloud account data:
{"Environment": "public", "AzureRMUseManagedIdentity": false, "AzureResourceGroup": "te-7ef-rg", "AzureRMApplicationId": "444444444444444444444", "AzureRMApplicationSecret": "dddddddddddddddddddd", "AzureRMSubscriptionId": "444444333333333333333", "AzureRMTenantId": "2222222222222222", "DefaultAccount": true, "Location": "westeurope", "Name": "azure", "Provider": "azure", "ProviderId": "99999999999999", "RMStorageAccount": "hpcscycle313b6dcesta", "RMStorageContainer": "cyclecloud"}
Exception in thread "main" java.lang.NullPointerException
        at com.cyclecomputing.appsupport.restlet.command.ConsoleCommandExecutor.makeRequest(ConsoleCommandExecutor.java:239)
        at com.cyclecomputing.appsupport.restlet.command.ConsoleCommandExecutor.run(ConsoleCommandExecutor.java:179)
        at com.cyclecomputing.grid.common.plugin.CommandExecutorApplication.main(CommandExecutorApplication.java:148)

Aborted
Error with cmd: ['/opt/cycle_server/cycle_server', 'execute', 'update Application.Setting set Value = false where Name == "authorization.check_datastore_permissions"']
Output: b''
Deployment failed...   Staying alive for DEBUGGING

```

**Comment by tbugfinder** [comment]
rebuilt everything few more times and didn't get it again within last build
